// <auto-generated />
using System;
using Database.RuntimeJournal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.RuntimeJournal.Migrations
{
    [DbContext(typeof(RuntimeExceptionsDatabaseContext))]
    [Migration("20250713135315_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.RuntimeJournal.Models.DbApplicationJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JournalHeader")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("JournalParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("JournalParentId");

                    b.HasIndex("JournalHeader", "JournalParentId")
                        .IsUnique();

                    b.ToTable("journals_n4", "journal");
                });

            modelBuilder.Entity("Database.RuntimeJournal.Models.DbApplicationJournal", b =>
                {
                    b.HasOne("Database.RuntimeJournal.Models.DbApplicationJournal", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("JournalParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Database.RuntimeJournal.Models.DbApplicationJournal", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
